#!/bin/sh

ainsl -v /etc/network/interfaces 'auto lo'
ainsl -v /etc/network/interfaces 'iface lo inet loopback'
ainsl -v /etc/network/interfaces 'auto eth0'

# enable dhcp for up to 8 attached interfaces
for i in 0 1 2 3 4 5 6 7 8; do
    ainsl -v /etc/network/interfaces "iface eth${i} inet dhcp"
done

