#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# currently missing from bootstrap-vz:
# init.d/expand-root
# init.d/generate-ssh-hostkeys (currently done in rc.local/CLOUD)
