#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# currently missing from bootstrap-vz:
# init.d/expand-root

ainsl -av /etc/sysctl.d/70-disable-ipv6.conf 'net.ipv6.conf.all.disable_ipv6 = 1'
ainsl -av /etc/sysctl.d/70-disable-ipv6.conf 'net.ipv6.conf.lo.disable_ipv6 = 0'

# Note from jimmy@d.o: Right now, GCE's vendor code which runs at every boot
# does not correctly handle the case where no SSH host keys are present,
# failing to generate them and preventing SSH from starting. We've discussed
# with Google and identified a logic fix to their vendor code to handle this
# acceptably, which they are planning to implement. Until this happens, we're
# recreating the host key files as empty files so that GCE knows which keys to
# generate.

for cipher in ed25519 ecdsa rsa; do
  touch "$target/etc/ssh/ssh_host_${cipher}_key"
done
