#!/bin/bash
set -euE

mkdir -p "$FAI_ROOT"/boot/grub

# Call `grub-mkconfig` while using our own `grub-probe`.
# `pkgdatadir` can be defined from the outside and is used to find
# `grub-mkconfig_lib`.  `grub-mkconfig_lib` is then used to set a different
# path for `grub-probe`.  `grub-mkconfig` won't emit root with UUID/PARTUUID,
# if it can't find them in `/dev/disks`, so use a static string and replace it
# here.
pkgdatadir=/run/grub $ROOTCMD grub-mkconfig | \
  sed \
    -e "s|##DEV##|PARTUUID=${PARTUUID_ROOT}|" \
    -e "s|##FSUUID##|${FSUUID_ROOT}|" \
    -e "s|##PARTUUID##|${PARTUUID_ROOT}|" \
  > "$FAI_ROOT"/boot/grub/grub.cfg
