#!/usr/bin/python3

import argparse
import json
import os
import subprocess

from debian_cloud_images.utils import argparse_ext
from debian_cloud_images.api.cdo.build import Build
from debian_cloud_images.api.registry import registry as api_registry


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--name',
        action=argparse_ext.ActionEnv,
        env='CLOUD_BUILD_NAME',
    )
    parser.add_argument('--output-dir',
        action=argparse_ext.ActionEnv,
        env='CLOUD_BUILD_OUTPUT_DIR',
    )
    parser.add_argument('--root',
        action=argparse_ext.ActionEnv,
        env='FAI_ROOT',
    )

    args = parser.parse_args()

    with subprocess.Popen(
        ('dpkg-query', '-W', '--admindir', os.path.join(args.root, 'var/lib/dpkg')),
        stdout=subprocess.PIPE,
    ) as f:
        packages = []
        for l in f.stdout:
            package, version = l.decode().strip().split()
            packages.append({'name': package, 'version': version})

    manifest = Build(packages=packages)
    with open('{}/{}.build-fai.json'.format(args.output_dir, args.name), 'w') as f:
        json.dump(api_registry.dump(manifest), f, indent=4, separators=(',', ': '), sort_keys=True)
