# After modifications, please call:
# "python3 -m debian_cloud_images.cli.generate_ci .gitlab/ci/generated.yml"
---
apiVersion: cloud.debian.org/v1alpha1
kind: ImageConfig

archs:
- name: amd64
  azureName: X64
  faiClasses: [AMD64, GRUB_CLOUD_AMD64]
- name: arm64
  azureName: Arm64
  faiClasses: [ARM64, GRUB_EFI_ARM64]
- name: ppc64el
  faiClasses: [PPC64EL, GRUB_IEEE1275]

releases:
- name: buster
  basename: buster
  id: '10'
  baseid: '10'
  faiClasses: [BUSTER, LINUX_VERSION_BUSTER, EXTRAS]
  matches:
  - matchArches: [amd64, arm64]
- name: buster-backports
  basename: buster-backports
  id: 10-backports
  baseid: '10'
  faiClasses: [BUSTER, LINUX_VERSION_BUSTER_LTS, EXTRAS]
  matches:
  - matchArches: [amd64, arm64]
- name: bullseye
  basename: bullseye
  id: '11'
  baseid: '11'
  faiClasses: [BULLSEYE, LINUX_VERSION_BASE, EXTRAS]
- name: bullseye-backports
  basename: bullseye-backports
  id: 11-backports
  baseid: '11'
  faiClasses: [BULLSEYE, LINUX_VERSION_BACKPORTS, EXTRAS]
- name: bookworm
  basename: bookworm
  id: '12'
  baseid: '12'
  faiClasses: [BOOKWORM, LINUX_VERSION_BASE, EXTRAS]
- name: bookworm-backports
  basename: bookworm-backports
  id: 12-backports
  baseid: '12'
  faiClasses: [BOOKWORM, LINUX_VERSION_BACKPORTS, EXTRAS]
- name: trixie
  basename: trixie
  id: '13'
  baseid: '13'
  faiClasses: [TRIXIE, LINUX_VERSION_BASE, EXTRAS]
- name: sid
  basename: sid
  id: sid
  baseid: sid
  faiClasses: [SID, LINUX_VERSION_BASE, EXTRAS]

vendors:
- name: azure
  faiClasses: [AZURE, LINUX_VARIANT_CLOUD, TIME_CHRONY, IPV6_DHCP]
  size: 30
  matches:
  - matchArches: [amd64]
  - matchArches: [arm64]
    matchReleases: [buster, buster-backports, bullseye]
    op: Disable
  - matchArches: [arm64]
- name: ec2
  faiClasses: [EC2, LINUX_VARIANT_CLOUD, TIME_SYSTEMD, IPV6_DHCP]
  size: 8
  matches:
  - matchArches: [amd64, arm64]
- name: gce
  faiClasses: [GCE, LINUX_VARIANT_CLOUD, TIME_SYSTEMD]
  size: 10
  matches:
  - matchReleases: [bullseye]
    op: Disable
  - matchArches: [amd64]
- name: generic
  faiClasses: [GENERIC, LINUX_VARIANT_BASE, TIME_SYSTEMD]
  size: 2
- name: genericcloud
  faiClasses: [GENERIC, LINUX_VARIANT_CLOUD, TIME_SYSTEMD]
  size: 2
  matches:
  - matchReleases: [buster]
    matchArches: [arm64]
    op: Disable
  - matchArches: [amd64, arm64]
- name: nocloud
  faiClasses: [NOCLOUD, LINUX_VARIANT_BASE, TIME_SYSTEMD]
  size: 2

types:
- name: dev
  faiClasses: [TYPE_DEV]
  outputName: 'debian-{release}-{vendor}-{arch}-{build_type}-{build_id}-{version}'
  outputVersion: '{version}'
  outputVersionAzure: '0.0.{version!s}'
- name: official
  outputName: 'debian-{release}-{vendor}-{arch}-{build_type}-{version}'
  outputVersion: '{date}-{version}'
  outputVersionAzure: '0.{date!s}.{version!s}'

publicTypes:
- name: dev
- name: daily
  matches:
  - matchVendors: [azure]
    matchReleases: [buster, buster-backports]
    uploadGroup: debian-10-daily
    op: EnableUpload
  - matchVendors: [azure]
    matchReleases: [bullseye, bullseye-backports]
    uploadGroup: debian-11-daily
    op: EnableUpload
  - matchVendors: [azure]
    matchReleases: [bookworm, bookworm-backports]
    uploadGroup: debian-12-daily
    op: EnableUpload
  - matchVendors: [azure]
    matchReleases: [trixie, trixie-backports]
    uploadGroup: debian-13-daily
    op: EnableUpload
  - matchVendors: [azure]
    matchReleases: [sid]
    uploadGroup: debian-sid-daily
    op: EnableUpload
  - matchVendors: [ec2]
    op: EnableUpload
  - matchVendors: [generic, genericcloud, nocloud]
- name: release
  matches:
  - matchReleases: [sid]
    op: Disable
  - matchReleases: [trixie]
    op: Disable
  - matchVendors: [azure]
    matchReleases: [buster, buster-backports]
    uploadGroup: debian-10
    op: EnableUpload
  - matchVendors: [azure]
    matchReleases: [bullseye, bullseye-backports]
    uploadGroup: debian-11
    op: EnableUpload
  - matchVendors: [azure]
    matchReleases: [bookworm, bookworm-backports]
    uploadGroup: debian-12
    op: EnableUpload
  - matchVendors: [ec2]
    op: EnableUpload
  - matchVendors: [generic, genericcloud]
